# Generated by Django 3.2 on 2022-12-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0004_businessmaquila_historicalbusinessmaquila'),
        ('products', '0003_auto_20221204_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpackingproduct',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='packingproduct',
            name='docs',
        ),
        migrations.AlterField(
            model_name='packingproduct',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='business_partners.providerpacking', verbose_name='Proveedor'),
        ),
    ]
