# Generated by Django 3.2 on 2023-01-23 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_auto_20221216_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('V', 'Variable'), ('F', 'Fijo')], max_length=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categoría',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kg_processed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Kg Procesados')),
                ('kg_total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Kg PT')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_category', to='products.fruits', verbose_name='Materia prima')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reporte',
            },
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_category', to='costs.category')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_category', to='costs.report')),
            ],
            options={
                'verbose_name': 'Reporte Categoría',
                'verbose_name_plural': 'Reporte Categoría',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='item',
            field=models.ManyToManyField(related_name='reports', through='costs.ReportCategory', to='costs.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('date',)},
        ),
    ]
