# Generated by Django 3.2 on 2023-01-17 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categoría',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='costs.category')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidad',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accounting_acount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('V', 'Variable'), ('F', 'Fixed')], max_length=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subgroups', to='costs.group')),
            ],
            options={
                'verbose_name': 'Subgrupo',
                'verbose_name_plural': 'Subgrupo',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='costs.modality'),
        ),
    ]
