# Generated by Django 3.2 on 2023-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='type',
            field=models.CharField(choices=[('V', 'Variable'), ('F', 'Fijo')], max_length=1),
        ),
    ]
