# Generated by Django 3.2 on 2023-01-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('V', 'Variable'), ('F', 'Fijo')], max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='report',
            name='item',
            field=models.ManyToManyField(related_name='reports', through='costs.ReportCategory', to='costs.Category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_category', to='costs.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='reportcategory',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_category', to='costs.report', verbose_name='Reporte'),
        ),
    ]
