# Generated by Django 3.2 on 2023-01-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0002_alter_subgroup_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reporte',
            },
        ),
        migrations.CreateModel(
            name='ReportSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_subgroups', to='costs.report')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_subgroups', to='costs.subgroup')),
            ],
            options={
                'verbose_name': 'Reporte Subgrupo',
                'verbose_name_plural': 'Reporte Subgrupo',
            },
        ),
        migrations.AddField(
            model_name='report',
            name='cost',
            field=models.ManyToManyField(related_name='reports', through='costs.ReportSubGroup', to='costs.SubGroup'),
        ),
    ]
