# Generated by Django 3.2 on 2023-01-24 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20221216_1327'),
        ('costs', '0002_auto_20230123_1540'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportCost',
        ),
        migrations.AlterModelOptions(
            name='reportcategory',
            options={'ordering': ['category__type'], 'verbose_name': 'Reporte Categoría', 'verbose_name_plural': 'Reporte Categoría'},
        ),
    ]
