# Generated by Django 3.2 on 2023-01-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0004_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubgroup',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='subgroup.cost', max_digits=10),
        ),
    ]
