# Generated by Django 3.2 on 2023-01-17 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0005_alter_reportsubgroup_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubgroup',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_groups', to='costs.report'),
        ),
    ]
