# Generated by Django 3.2 on 2023-01-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0009_auto_20230106_0941'),
        ('costs', '0006_alter_reportsubgroup_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='kg_processed',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Kg Procesados'),
        ),
        migrations.AddField(
            model_name='report',
            name='kg_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Kg Totales'),
        ),
        migrations.AddField(
            model_name='report',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports_cost', to='raw_material.lot', verbose_name='Lote'),
        ),
    ]
