# Generated by Django 3.2 on 2023-01-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0007_auto_20230117_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='accounting_acount',
            field=models.CharField(max_length=100),
        ),
    ]
