# Generated by Django 3.2 on 2023-01-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0008_alter_subgroup_accounting_acount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('date',)},
        ),
        migrations.AlterUniqueTogether(
            name='reportsubgroup',
            unique_together={('report', 'subgroup')},
        ),
    ]
