# Generated by Django 3.2 on 2023-01-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_auto_20230117_1645'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportsubgroup',
            unique_together=set(),
        ),
    ]
