# Generated by Django 3.2 on 2023-01-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0010_alter_reportsubgroup_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportsubgroup',
            unique_together={('report', 'subgroup')},
        ),
    ]
