# Generated by Django 3.2 on 2023-01-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0013_alter_reportsubgroup_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='cost',
            new_name='item',
        ),
    ]
