# Generated by Django 3.2 on 2023-01-10 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0009_auto_20230106_0941'),
        ('report', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPTPineapple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_process', models.DateField(verbose_name='Fecha de Proceso')),
                ('kg_processed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Procesados')),
                ('kg_discarded', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Descartados')),
                ('merma', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Merma')),
                ('shell', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cascara y tronco')),
                ('crown', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Corona')),
                ('juice_pulp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Jugo y pulpa')),
                ('retail_rings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rings retail')),
                ('retail_1_8', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1/8 retail')),
                ('retail_1_16', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1/16 retail')),
                ('granel_rings', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rings granel')),
                ('granel_1_16', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1/16 granel')),
                ('granel_1_8', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='1/8 granel')),
                ('target', models.IntegerField(default=20, verbose_name='Target')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_pt_pineapple', to='raw_material.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Reporte PT Piña',
                'verbose_name_plural': 'Reportes PT Piña',
                'ordering': ['-date_process'],
            },
        ),
        migrations.CreateModel(
            name='ReportPTMango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_process', models.DateField(verbose_name='Fecha de Proceso')),
                ('kg_processed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Procesados')),
                ('kg_discarded', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Descartados')),
                ('merma', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Merma')),
                ('shell', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cascara')),
                ('retail_slices', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Slices retail')),
                ('retail_cachetes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cachetes retail')),
                ('retail_chunks', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chunks retail')),
                ('retail_cubs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cubs retail')),
                ('granel_slices', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Slices granel')),
                ('granel_cachetes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cachetes granel')),
                ('granel_chunks', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chunks granel')),
                ('granel_cubs', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cubs granel')),
                ('recoverable', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Recuperable')),
                ('target', models.IntegerField(default=11, verbose_name='Target')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_pt_mango', to='raw_material.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Reporte PT Mango',
                'verbose_name_plural': 'Reportes PT Mango',
                'ordering': ['-date_process'],
            },
        ),
        migrations.CreateModel(
            name='ReportPTGoldenberry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_process', models.DateField(verbose_name='Fecha de Proceso')),
                ('kg_processed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Procesados')),
                ('kg_discarded', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Descartados')),
                ('merma', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Merma')),
                ('caliz', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Caliz')),
                ('retail_whole', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Enteros retail')),
                ('retail_halves', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mitades retail')),
                ('retail_quarter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cuartos retail')),
                ('granel_whole', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Enteros granel')),
                ('granel_halves', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mitades granel')),
                ('granel_quarter', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cuartos granel')),
                ('target', models.IntegerField(default=20, verbose_name='Target')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_pt_goldenberry', to='raw_material.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Reporte PT Aguaymanto',
                'verbose_name_plural': 'Reportes PT Aguaymanto',
                'ordering': ['-date_process'],
            },
        ),
        migrations.CreateModel(
            name='ReportPTBlueberry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_process', models.DateField(verbose_name='Fecha de Proceso')),
                ('kg_processed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Procesados')),
                ('kg_discarded', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Descartados')),
                ('merma', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Merma')),
                ('retail_whole', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Enteros retail')),
                ('retail_halves', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mitades retail')),
                ('granel_whole', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Enteros granel')),
                ('granel_halves', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mitades granel')),
                ('target', models.IntegerField(default=20, verbose_name='Target')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_pt_blueberry', to='raw_material.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Reporte PT Arándanos',
                'verbose_name_plural': 'Reportes PT Arándanos',
                'ordering': ['-date_process'],
            },
        ),
        migrations.CreateModel(
            name='ReportPTBanana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_process', models.DateField(verbose_name='Fecha de Proceso')),
                ('kg_processed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Procesados')),
                ('kg_discarded', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Descartados')),
                ('merma', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Merma')),
                ('shell', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cascara')),
                ('retail_slices', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Slices retail')),
                ('retail_coins', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coins retail')),
                ('granel_slices', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Slices granel')),
                ('granel_coins', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Coins granel')),
                ('target', models.IntegerField(default=11, verbose_name='Target')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_pt_banana', to='raw_material.lot', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Reporte PT Banana',
                'verbose_name_plural': 'Reportes PT Banana',
                'ordering': ['-date_process'],
            },
        ),
    ]
