# Generated by Django 3.2 on 2023-01-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reportptbanana_reportptblueberry_reportptgoldenberry_reportptmango_reportptpineapple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportptbanana',
            name='granel_coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coins granel'),
        ),
        migrations.AlterField(
            model_name='reportptbanana',
            name='granel_slices',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Slices granel'),
        ),
        migrations.AlterField(
            model_name='reportptbanana',
            name='kg_discarded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Descartados'),
        ),
        migrations.AlterField(
            model_name='reportptbanana',
            name='kg_processed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Procesados'),
        ),
        migrations.AlterField(
            model_name='reportptbanana',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='reportptbanana',
            name='retail_coins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coins retail'),
        ),
        migrations.AlterField(
            model_name='reportptbanana',
            name='retail_slices',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Slices retail'),
        ),
        migrations.AlterField(
            model_name='reportptbanana',
            name='shell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cascara'),
        ),
        migrations.AlterField(
            model_name='reportptblueberry',
            name='granel_halves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mitades granel'),
        ),
        migrations.AlterField(
            model_name='reportptblueberry',
            name='granel_whole',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Enteros granel'),
        ),
        migrations.AlterField(
            model_name='reportptblueberry',
            name='kg_discarded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Descartados'),
        ),
        migrations.AlterField(
            model_name='reportptblueberry',
            name='kg_processed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Procesados'),
        ),
        migrations.AlterField(
            model_name='reportptblueberry',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='reportptblueberry',
            name='retail_halves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mitades retail'),
        ),
        migrations.AlterField(
            model_name='reportptblueberry',
            name='retail_whole',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Enteros retail'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='caliz',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Caliz'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='granel_halves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mitades granel'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='granel_quarter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cuartos granel'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='granel_whole',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Enteros granel'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='kg_discarded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Descartados'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='kg_processed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Procesados'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='retail_halves',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mitades retail'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='retail_quarter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cuartos retail'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='retail_whole',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Enteros retail'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='granel_cachetes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cachetes granel'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='granel_chunks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chunks granel'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='granel_cubs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cubs granel'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='granel_slices',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Slices granel'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='kg_discarded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Descartados'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='kg_processed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Procesados'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='recoverable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Recuperable'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='retail_cachetes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cachetes retail'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='retail_chunks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chunks retail'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='retail_cubs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cubs retail'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='retail_slices',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Slices retail'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='shell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cascara'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='crown',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Corona'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='granel_1_16',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='1/16 granel'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='granel_1_8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='1/8 granel'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='granel_rings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rings granel'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='juice_pulp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jugo y pulpa'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='kg_discarded',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Descartados'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='kg_processed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Procesados'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='retail_1_16',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='1/16 retail'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='retail_1_8',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='1/8 retail'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='retail_rings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rings retail'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='shell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cascara y tronco'),
        ),
    ]
