# Generated by Django 3.2 on 2023-01-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20230110_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportptbanana',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='reportptblueberry',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='reportptgoldenberry',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='reportptmango',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Merma'),
        ),
        migrations.AlterField(
            model_name='reportptpineapple',
            name='merma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Merma'),
        ),
    ]
