# Generated by Django 3.2 on 2022-12-16 14:39

import apps.raw_material.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0005_auto_20221207_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='invoice',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='tc',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='TC'),
        ),
        migrations.AddField(
            model_name='lot',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to=apps.raw_material.models.custom_invoice_file_path, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='lot',
            name='tc',
            field=models.FileField(blank=True, null=True, upload_to=apps.raw_material.models.custom_tc_file_path, verbose_name='TC'),
        ),
    ]
