# Generated by Django 3.2 on 2023-01-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0007_auto_20221216_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalilot',
            name='type',
            field=models.CharField(choices=[('C', 'COMPLETE'), ('M', 'MODIFIED'), ('S', 'SPLIT')], default='C', max_length=1, verbose_name='Tipo de pallet'),
        ),
        migrations.AddField(
            model_name='ilot',
            name='type',
            field=models.CharField(choices=[('C', 'COMPLETE'), ('M', 'MODIFIED'), ('S', 'SPLIT')], default='C', max_length=1, verbose_name='Tipo de pallet'),
        ),
    ]
