# Generated by Django 3.2 on 2023-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0008_auto_20230103_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo de factura'),
        ),
        migrations.AddField(
            model_name='lot',
            name='invoice_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo de factura'),
        ),
    ]
