# Generated by Django 3.2 on 2022-12-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221217_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluseraccount',
            name='role',
            field=models.CharField(choices=[('1', 'Operaciones'), ('2', 'Logistica'), ('3', 'Certificaciones'), ('4', 'Administración'), ('5', 'Calidad'), ('6', 'Materia Prima'), ('7', 'Producción'), ('8', 'Visualizador'), ('9', 'Compras'), ('10', 'Mantenimiento')], default='8', max_length=2),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('1', 'Operaciones'), ('2', 'Logistica'), ('3', 'Certificaciones'), ('4', 'Administración'), ('5', 'Calidad'), ('6', 'Materia Prima'), ('7', 'Producción'), ('8', 'Visualizador'), ('9', 'Compras'), ('10', 'Mantenimiento')], default='8', max_length=2),
        ),
    ]
