# Generated by Django 3.2 on 2022-12-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_auto_20221204_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysismango',
            name='brix_10_12',
        ),
        migrations.RemoveField(
            model_name='analysismango',
            name='brix_13',
        ),
        migrations.RemoveField(
            model_name='analysismango',
            name='brix_7_9',
        ),
        migrations.RemoveField(
            model_name='historicalanalysismango',
            name='brix_10_12',
        ),
        migrations.RemoveField(
            model_name='historicalanalysismango',
            name='brix_13',
        ),
        migrations.RemoveField(
            model_name='historicalanalysismango',
            name='brix_7_9',
        ),
        migrations.AddField(
            model_name='analysisaguaymanto',
            name='caliz',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Caliz'),
        ),
        migrations.AddField(
            model_name='analysisaguaymanto',
            name='small',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Pequeño < 17mm'),
        ),
        migrations.AddField(
            model_name='analysismango',
            name='brix_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix < 7'),
        ),
        migrations.AddField(
            model_name='analysismango',
            name='brix_7_8',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix 7-8'),
        ),
        migrations.AddField(
            model_name='analysismango',
            name='brix_8_9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix 8-9'),
        ),
        migrations.AddField(
            model_name='analysismango',
            name='brix_9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix > 9'),
        ),
        migrations.AddField(
            model_name='analysismango',
            name='color_3_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 3,5'),
        ),
        migrations.AddField(
            model_name='historicalanalysisaguaymanto',
            name='caliz',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Caliz'),
        ),
        migrations.AddField(
            model_name='historicalanalysisaguaymanto',
            name='small',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Pequeño < 17mm'),
        ),
        migrations.AddField(
            model_name='historicalanalysismango',
            name='brix_7',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix < 7'),
        ),
        migrations.AddField(
            model_name='historicalanalysismango',
            name='brix_7_8',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix 7-8'),
        ),
        migrations.AddField(
            model_name='historicalanalysismango',
            name='brix_8_9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix 8-9'),
        ),
        migrations.AddField(
            model_name='historicalanalysismango',
            name='brix_9',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Brix > 9'),
        ),
        migrations.AddField(
            model_name='historicalanalysismango',
            name='color_3_5',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Color 3,5'),
        ),
    ]
