# Generated by Django 3.2 on 2023-01-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0005_auto_20230103_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysismango',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='analysismango',
            name='soft',
        ),
        migrations.RemoveField(
            model_name='historicalanalysismango',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='historicalanalysismango',
            name='soft',
        ),
        migrations.AddField(
            model_name='analysismango',
            name='overripe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Sobre maduro'),
        ),
        migrations.AddField(
            model_name='historicalanalysismango',
            name='overripe',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Sobre maduro'),
        ),
        migrations.AlterField(
            model_name='analysismango',
            name='mature',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='maduro'),
        ),
        migrations.AlterField(
            model_name='analysismango',
            name='rot',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Podrido'),
        ),
        migrations.AlterField(
            model_name='historicalanalysismango',
            name='mature',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='maduro'),
        ),
        migrations.AlterField(
            model_name='historicalanalysismango',
            name='rot',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True, verbose_name='Podrido'),
        ),
    ]
