# Generated by Django 3.2 on 2022-12-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorpineapple',
            name='price_objective',
        ),
    ]
