# Generated by Django 3.2 on 2022-12-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raw_material', '0007_auto_20221216_1513'),
        ('planning', '0002_remove_indicatorpineapple_price_objective'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndicatorAguaymanto',
            new_name='IndicatorKPIAguaymanto',
        ),
        migrations.RenameModel(
            old_name='IndicatorMango',
            new_name='IndicatorKPIMango',
        ),
        migrations.RenameModel(
            old_name='IndicatorPineapple',
            new_name='IndicatorKPIPineapple',
        ),
    ]
