# Generated by Django 3.2 on 2022-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_auto_20221221_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorkpipineapple',
            name='price_objective',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='price_objective',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='price_objective',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
