# Generated by Django 3.2 on 2022-12-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20221221_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorkpimango',
            options={'verbose_name': 'Indicador de Mango', 'verbose_name_plural': 'Indicador de Mango'},
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='entry_objective',
            field=models.IntegerField(default=100, verbose_name='Objetivo de ingreso'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='objective',
            field=models.IntegerField(default=90, verbose_name='Objetivo de producción'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='price_objective',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio objetivo'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='defects_objective',
            field=models.IntegerField(default=15, verbose_name='Objetivo de defectos'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='entry_objective',
            field=models.IntegerField(default=100, verbose_name='Objetivo de ingreso'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='objective',
            field=models.IntegerField(default=90, verbose_name='Objetivo de producción'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='price_objective',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Precio objetivo'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='entry_objective',
            field=models.IntegerField(default=100, verbose_name='Objetivo de ingreso'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='objective',
            field=models.IntegerField(default=90, verbose_name='Objetivo de producción'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='price_objective',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio objetivo'),
        ),
    ]
