# Generated by Django 3.2 on 2022-12-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_auto_20221222_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorkpiaguaymanto',
            name='caliz',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Caliz'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='entry',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Ingreso proyectado'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='entry_objective',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Objetivo de ingreso'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='objective',
            field=models.IntegerField(blank=True, default=90, null=True, verbose_name='Objetivo de producción'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='price_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Precio objetivo'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='defects_objective',
            field=models.IntegerField(blank=True, default=15, null=True, verbose_name='Objetivo de defectos'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='entry',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Ingreso proyectado'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='entry_objective',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Objetivo de ingreso'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='objective',
            field=models.IntegerField(blank=True, default=90, null=True, verbose_name='Objetivo de producción'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='price_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Precio objetivo'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='entry',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Ingreso proyectado'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='entry_objective',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Objetivo de ingreso'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='objective',
            field=models.IntegerField(blank=True, default=90, null=True, verbose_name='Objetivo de producción'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='price_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Precio objetivo'),
        ),
    ]
