# Generated by Django 3.2 on 2022-12-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_auto_20221223_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorkpiaguaymanto',
            name='discard_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Caliz'),
        ),
    ]
