# Generated by Django 3.2 on 2022-12-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_indicatorkpiaguaymanto_discard_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorkpimango',
            name='defects_objective',
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='objective',
            field=models.IntegerField(blank=True, default=97, null=True, verbose_name='Objetivo de producción'),
        ),
    ]
