# Generated by Django 3.2 on 2022-12-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0009_auto_20221225_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='caliz',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Caliz'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='discard',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Descarte'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='discard_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=7, verbose_name='Caliz'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='objective',
            field=models.IntegerField(blank=True, default=90, verbose_name='Objetivo de producción'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='price_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio objetivo'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='objective',
            field=models.IntegerField(blank=True, default=97, verbose_name='Objetivo de producción'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='price_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio objetivo'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='objective',
            field=models.IntegerField(blank=True, default=90, verbose_name='Objetivo de producción'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='price_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, verbose_name='Precio objetivo'),
        ),
    ]
