# Generated by Django 3.2 on 2022-12-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_auto_20221226_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='date',
            field=models.DateField(unique=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='date',
            field=models.DateField(unique=True, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='date',
            field=models.DateField(unique=True, verbose_name='Fecha de ingreso'),
        ),
    ]
