# Generated by Django 3.2 on 2022-12-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_auto_20221226_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Fecha de ingreso')),
                ('consumption', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Consumo GLP')),
                ('kg_terminated', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Kg terminados')),
                ('objective_glp', models.DecimalField(blank=True, decimal_places=2, default=0.33, max_digits=3, verbose_name='Objetivo GLP')),
                ('kg_executed', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Kg ejecutados')),
                ('ability', models.IntegerField(blank=True, default=1800, verbose_name='Capacidad')),
                ('objective_machine', models.IntegerField(blank=True, default=90, verbose_name='Objetivo picadora')),
                ('works_scheduled', models.IntegerField(blank=True, default=0, verbose_name='Trabajos programados')),
                ('objective_works', models.IntegerField(blank=True, default=98, verbose_name='Objetivo de trabajos')),
                ('work_corrective', models.IntegerField(blank=True, default=0, verbose_name='Trabajos correctivos')),
                ('objective_corrective', models.IntegerField(blank=True, default=20, verbose_name='Objetivo de trabajos correctivos')),
                ('objective_preventive', models.IntegerField(blank=True, default=80, verbose_name='Objetivo de trabajos preventivos')),
                ('work_preventive', models.IntegerField(blank=True, default=0, verbose_name='Trabajos preventivos')),
                ('kg_defective', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Kg defectuosos')),
                ('kg_released', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Kg lanzados')),
                ('objective_pnd', models.IntegerField(blank=True, default=94, verbose_name='Objetivo de PND')),
            ],
            options={
                'verbose_name': 'Indicador de Mantenimiento',
                'verbose_name_plural': 'Indicador de Mantenimiento',
                'ordering': ['-date'],
            },
        ),
    ]
