# Generated by Django 3.2 on 2022-12-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_indicatormaintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorkpiaguaymanto',
            options={'ordering': ['-date'], 'verbose_name': 'Indicador de Aguaymanto', 'verbose_name_plural': 'Indicador de Aguaymanto'},
        ),
        migrations.AlterModelOptions(
            name='indicatorkpimango',
            options={'ordering': ['-date'], 'verbose_name': 'Indicador de Mango', 'verbose_name_plural': 'Indicador de Mango'},
        ),
        migrations.AlterModelOptions(
            name='indicatorkpipineapple',
            options={'ordering': ['-date'], 'verbose_name': 'Indicador de Piña', 'verbose_name_plural': 'Indicador de Piña'},
        ),
    ]
