# Generated by Django 3.2 on 2023-01-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_auto_20221230_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='entry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ingreso proyectado'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='kg_brute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Kg Bruto Procesado'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='discard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Descarte'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='entry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ingreso proyectado'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='kg_brute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Kg Bruto Procesado'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='discard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Descarte'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='entry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Ingreso proyectado'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='kg_brute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Kg Bruto Procesado'),
        ),
        migrations.AlterField(
            model_name='indicatorkpipineapple',
            name='price_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.66, max_digits=7, verbose_name='Precio objetivo'),
        ),
    ]
