# Generated by Django 3.2 on 2023-01-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0015_auto_20230103_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='caliz',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Caliz'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='discard',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Descarte'),
        ),
        migrations.AlterField(
            model_name='indicatorkpiaguaymanto',
            name='price_objective',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Precio objetivo'),
        ),
        migrations.AlterField(
            model_name='indicatorkpimango',
            name='price_objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.66, max_digits=7, null=True, verbose_name='Precio objetivo'),
        ),
        migrations.AlterField(
            model_name='indicatormaintenance',
            name='ability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad'),
        ),
        migrations.AlterField(
            model_name='indicatormaintenance',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Consumo GLP'),
        ),
        migrations.AlterField(
            model_name='indicatormaintenance',
            name='kg_defective',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Kg defectuosos'),
        ),
        migrations.AlterField(
            model_name='indicatormaintenance',
            name='kg_executed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Kg ejecutados'),
        ),
        migrations.AlterField(
            model_name='indicatormaintenance',
            name='kg_released',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Kg lanzados'),
        ),
        migrations.AlterField(
            model_name='indicatormaintenance',
            name='kg_terminated',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Kg terminados'),
        ),
        migrations.AlterField(
            model_name='indicatormaintenance',
            name='objective_glp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.33, max_digits=3, null=True, verbose_name='Objetivo GLP'),
        ),
    ]
