# Generated by Django 3.2 on 2023-01-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0016_auto_20230106_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndicatorMaintenance',
        ),
    ]
