# Generated by Django 3.2 on 2022-12-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0002_alter_cut_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cut',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cut',
            name='product',
        ),
    ]
