# Generated by Django 3.2 on 2022-12-07 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0004_businessmaquila_historicalbusinessmaquila'),
        ('commercial', '0004_auto_20221207_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='boxes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cajas'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='business_partners.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='commercial.condition', verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='expiring_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de producción'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4, null=True, verbose_name='Progreso'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='type_inf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='commercial.type', verbose_name='Tipo'),
        ),
    ]
