# Generated by Django 3.2 on 2022-12-10 10:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0008_historicalcondition_historicalcut_historicalfamily_historicalgroup_historicallot_historicalpacking_h'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['-id'], 'verbose_name': 'Lotes', 'verbose_name_plural': 'Lotes'},
        ),
        migrations.AddField(
            model_name='historicallot',
            name='slugi',
            field=models.SlugField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='slugi',
            field=models.SlugField(default=uuid.uuid4, null=True),
        ),
    ]
