# Generated by Django 3.2 on 2022-12-10 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0009_auto_20221210_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallot',
            name='slugi',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='slugi',
        ),
        migrations.AddField(
            model_name='historicallot',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
