# Generated by Django 3.2 on 2022-12-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0011_auto_20221210_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallot',
            name='objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='objective',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Objective'),
        ),
    ]
