# Generated by Django 3.2 on 2022-12-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0012_auto_20221210_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallot',
            name='client',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='client',
        ),
        migrations.AddField(
            model_name='historicallot',
            name='fosetyl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Fosetil'),
        ),
        migrations.AddField(
            model_name='historicallot',
            name='pesticides',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Pesticidas'),
        ),
        migrations.AddField(
            model_name='lot',
            name='fosetyl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Fosetil'),
        ),
        migrations.AddField(
            model_name='lot',
            name='pesticides',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Pesticidas'),
        ),
    ]
