# Generated by Django 3.2 on 2022-12-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0013_auto_20221212_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='bags',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cajas'),
        ),
        migrations.AddField(
            model_name='lot',
            name='bags',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cajas'),
        ),
    ]
