# Generated by Django 3.2 on 2022-12-12 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0004_businessmaquila_historicalbusinessmaquila'),
        ('commercial', '0015_auto_20221212_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallot',
            name='client',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business_partners.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='lot',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='business_partners.client', verbose_name='Cliente'),
        ),
    ]
