# Generated by Django 3.2 on 2022-12-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0018_auto_20221212_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallot',
            name='family',
        ),
        migrations.RemoveField(
            model_name='historicallot',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='family',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='stock',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commercial.family', verbose_name='Familia'),
        ),
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='commercial.family', verbose_name='Familia'),
        ),
        migrations.AlterUniqueTogether(
            name='kardexcommercial',
            unique_together={('date', 'lot')},
        ),
    ]
