# Generated by Django 3.2 on 2022-12-15 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_partners', '0004_businessmaquila_historicalbusinessmaquila'),
        ('warehouse', '0001_initial'),
        ('commercial', '0019_auto_20221212_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='cuts', to='commercial.product', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcut',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commercial.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='historicalvariety',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commercial.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='variety',
            name='product',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='varieties', to='commercial.product', verbose_name='Producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lot',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='business_partners.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='cut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cut', to='commercial.cut', verbose_name='Corte'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='fcl',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fcl_lot', to='warehouse.packinglist', verbose_name='FCL'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group', to='commercial.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packaging', to='commercial.packing', verbose_name='Embalaje'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='packing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='packing', to='commercial.packing', verbose_name='Empaque'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presentation', to='commercial.presentation', verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_lot', to='commercial.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider', to='business_partners.businessmaquila', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='type_inf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='type', to='commercial.type', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lot',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variety', to='commercial.variety', verbose_name='Variedad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='commercial.family', verbose_name='Familia'),
        ),
    ]
