# Generated by Django 3.2 on 2022-12-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercial', '0020_auto_20221215_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalcut',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='cut',
            unique_together={('name', 'product')},
        ),
    ]
