# Generated by Django 3.2 on 2022-12-30 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process_line', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocesslinereleased',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Kg por caja'),
        ),
        migrations.AddField(
            model_name='historicalprocesslinereleased',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Fecha de Actualización'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processlinereleased',
            name='kg',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True, verbose_name='Kg por caja'),
        ),
        migrations.AddField(
            model_name='processlinereleased',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
