# Generated by Django 3.2 on 2023-01-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process_line', '0006_auto_20230117_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processlineconditioning',
            options={'ordering': ['process_date'], 'verbose_name': 'Proceso de Acondicionado', 'verbose_name_plural': 'Proceso de Acondicionado'},
        ),
        migrations.AlterModelOptions(
            name='processlinereleased',
            options={'ordering': ['release_date'], 'verbose_name': 'Proceso de  Liberación', 'verbose_name_plural': 'Proceso de Liberación'},
        ),
        migrations.AlterModelOptions(
            name='processlineterminated',
            options={'ordering': ['packing_date'], 'verbose_name': 'Proceso de Envasado', 'verbose_name_plural': 'Proceso de Envasado'},
        ),
    ]
